config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('users/',include('users.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path,include
from . import views

app_name='posts'

urlpatterns = [
    path('', views.allPost_view, name="all_posts"),
    path('new-post/',views.newpost,name="new_post"),
    path('<slug:slug>',views.post_detail, name="page")
]

users/urls.py
from django.urls import path,include
from . import views

app_name='users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title=models.CharField(max_length=75)
    body=models.TextField()
    slug=models.SlugField()
    date=models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(upload_to='', default='1.png', blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,null=True, blank=True)

    
        

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms  
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model=models.Post
        fields=['title','body','slug','banner','author']

posts/views.py
from django.shortcuts import render
from .models import Post
from . import forms
from django.contrib.auth.decorators import login_required

# Create your views here.

def allPost_view(request):
    posts=Post.objects.all().order_by('-date')
    return render(request,"posts/allposts.html",{'posts':posts})

def post_detail(request,slug):
    post_page=Post.objects.get(slug=slug)
    return render(request,'posts/postPage.html',{'post':post_page})

@login_required(login_url="users:login")
def newpost(request):
    if request.method=="POST":
        form=forms.CreatePost(request.POST,request.FILES)
        if form.is_valid:
            newpost=form.save(commit=False)
            newpost.author=request.user
            newpost.save()
    else:
        form=forms.CreatePost()
    return render(request,"posts/newpost.html",{'form':form})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login,logout

# Create your views here.

def register_view(request):
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect("posts:all_posts")
    else:
        form=UserCreationForm()
    return render(request,'users/register.html',{'form':form})

def login_view(request):
    if request.method=="POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request,form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:all_posts")
    else:
        form=AuthenticationForm()
    return render(request,"users/login.html",{'form':form})

def logout_view(request):
    if request.method=="POST":
        logout(request)
        return redirect("posts:all_posts")

posts/templates/posts/allposts.html
{% extends 'layout.html' %}
{% load static %}

{% block title%}
    blog-project
{% endblock %}

{% block content %}
    <div class="postsdiv">
        <h1 class="heading">All Posts</h1>
        {% for post in posts %}
        <div class="eachpost">
            <button onclick="window.location.href='{% url 'posts:page' slug=post.slug %}'">Read</button>
            <div>
                <h2>{{post.author}}:{{post.title}}</h2>
                <p>{{post.body}}</p>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/newpost.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    New Post
{% endblock %}

{% block content %}
<div class="newPostDiv">
    <h1>Create New Post</h1>
    <form action="{% url 'posts:new_post' %}" method="POST" enctype="multipart/form-data" class="newPostForm">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submitBtn">Add Post</button>
    </form>
</div>
{% endblock %}

posts/templates/posts/postPage.html
{% extends 'layout.html' %}
{% load static %}

{% block title%}
    postPage
{% endblock %}

{% block content %}
<div class="postpage">
    <h1>{{post.author}}:{{post.title}}</h1>
    <div>
        <p>{{post.body}}</p>
        <img src="{{post.banner.url}}" />
    </div>
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            BlogProject
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>

<body>
    <div class="wrapper">
        <nav>
            <ul>
                <li><a href="{% url 'posts:all_posts' %}">Home</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'posts:new_post' %}">Add New Post</a></li>
                    <li>
                        <form method="POST" action="{% url 'users:logout' %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-link-button">Logout</button>
                        </form>
                    </li>
                {% else %}
                    <li><a href="{% url 'users:login' %}">Login</a></li>
                    <li><a href="{% url 'users:register' %}">Register</a></li>
                {% endif %}
            </ul>
        </nav>

        <main>
            {% block content %}
                <p>default content</p>
            {% endblock %}
        </main>

        <footer>
            <p>Blog Project</p>
        </footer>
    </div>
</body>
</html>

users/templates/users/login.html
{% extends "layout.html" %}
{% load static %}

{% block title%}
    Login Page
{% endblock %}

{% block content %}
<div class="loginDiv">
    <h2>Login to Account</h2>
    <form action="{% url 'users:login' %}" method="POST" class="loginForm">
        {% csrf_token %}
        {{ form.as_p }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}"/>
        {% endif %}
        <button type="submit" class="submitBtn">Submit</button>
    </form>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'layout.html' %}
{% load static %}

{% block title%}
    Registeration Page
{% endblock %}

{% block content %}
<div class="registerDiv">
    <h2>Create an Account</h2>
    <form action="{% url 'users:register' %}" method="POST" class="registerForm">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="submitBtn">Submit</button>
    </form>
</div>
{% endblock %}